# Generated by Django 6.0.2 on 2026-02-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.IntegerField()),
                ('usuario', models.CharField(max_length=100)),
                ('data', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numsala', models.IntegerField()),
                ('andar', models.IntegerField()),
                ('recursos', models.CharField(max_length=100)),
                ('capacidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('ativo', models.BooleanField()),
                ('nivel', models.CharField(max_length=100)),
            ],
        ),
    ]
