# Generated by Django 6.0.2 on 2026-02-25 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('nivel', models.CharField(default='1', max_length=100)),
                ('foto_perfil', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numsala', models.IntegerField()),
                ('capacidade', models.IntegerField()),
                ('disponivel', models.BooleanField(default=True)),
                ('dia_nao_disponivel', models.DateField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('recursos', models.ManyToManyField(blank=True, to='core.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField(default=None)),
                ('hora_inicio', models.TimeField(default=None)),
                ('hora_fim', models.TimeField(default=None)),
                ('multa', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('preco_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sala')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.usuario')),
            ],
        ),
    ]
