# Generated by Django 6.0.2 on 2026-02-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_ativo_alter_usuario_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.URLField(blank=True, null=True),
        ),
    ]
