# Generated by Django 6.0.2 on 2026-02-24 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='nome',
        ),
    ]
